AWSTemplateFormatVersion: "2010-09-09"
Description: Create Client

Parameters:
  ProjectName:
    Type: String
    Description: Project Name for all
  KeyName:
    Type: String
    Description: EC2 key pair
  MyHomeIP:
    Type: String
    Description: Muy Home IP address

Resources:
  ############################################
  #### EC2                                ####
  ############################################
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-03f584e50b2d32776
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
          SubnetId: { "Fn::ImportValue": !Sub "${ProjectName}-PriSub1aId" }
          GroupSet:
            - !Ref EC2sgClient
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-ec2-client

  ############################################
  #### security group                     ####
  ############################################
  EC2sgClient:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${ProjectName}-ec2-client-sg
      GroupName: !Sub ${ProjectName}-ec2-client-sg
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 65535
          DestinationSecurityGroupId:
            { "Fn::ImportValue": !Sub "${ProjectName}-ec2-proxy-sg" }
        - IpProtocol: tcp
          FromPort: 53
          ToPort: 53
          DestinationSecurityGroupId:
            { "Fn::ImportValue": !Sub "${ProjectName}-ec2-dns-sg" }
        - IpProtocol: udp
          FromPort: 53
          ToPort: 53
          DestinationSecurityGroupId:
            { "Fn::ImportValue": !Sub "${ProjectName}-ec2-dns-sg" }
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId:
            { "Fn::ImportValue": !Sub "${ProjectName}-ec2-proxy-bastion-sg" }
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-ec2-client-sg
      VpcId: { "Fn::ImportValue": !Sub "${ProjectName}-VpcId" }

  ############################################
  #### Delete Stack Sceduler              ####
  ############################################
  EventSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: "Delete Schedule"
      ScheduleExpression: !Sub "cron(00 02 ? * * *)"
      ScheduleExpressionTimezone: "Asia/Tokyo"
      FlexibleTimeWindow:
        Mode: "OFF"
      State: ENABLED
      Target:
        Arn: "arn:aws:scheduler:::aws-sdk:cloudformation:deleteStack"
        Input: !Sub '{ "StackName": "${AWS::StackName}" }'
        RoleArn: !ImportValue DeleteSchedulerRoleARN

############################################
#### OutPuts                            ####
############################################
Outputs:
  EC2:
    Value: !Ref EC2
    Description: EC2 Proxy Client
    Export:
      Name: !Sub ${ProjectName}-ec2-proxy-client
  EC2sgClient:
    Value:
      Fn::GetAtt:
        - EC2sgClient
        - GroupId
    Description: Proxy EC2sg client
    Export:
      Name: !Sub ${ProjectName}-ec2-proxy-client-sg
